### ISSUE TITLE
스플래시 설정 시 안드로이드에서는 빌드 에러 발생

### ISSUE THREAD

**Issue by drizzle96** [team-bbtrain/BabBBu#72]
### 해결법
스플래시 설정 파일에 안드로이드 12 용 코드 추가

```
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png

  android_gravity: fill
  ios_content_mode: scaleAspectFill

  android_12:
    image: assets/app_icon.png
    icon_background_color: "#FFFFFF"

```
